// ReadConfig.java 
public String getUserEmail() {
    String email = pro.getProperty("useremail"); 
    return email;
}

public String getPassword() {
    String password = pro.getProperty("password");
    return password;
}